POST http://localhost:8181/v1/compile?explain=true&explain=fails
Content-Type: application/json

{}

###
POST http://localhost:8181/v1/compile?explain=true&explain=fails
Content-Type: application/json

{
  "query": "data.example.allow == true",
  "input": {
    "subject": {
      "clearance_level": 4
    }
  },
  "options": {
    "disableInlining": []
  },
  "unknowns": [
    "data.reports"
  ]
}

